#pragma once

/**
 * Name: Outlast_Trials
 * Version: 1.3
 */

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
	// --------------------------------------------------
	// # Classes
	// --------------------------------------------------
	/**
	 * AnimBlueprintGeneratedClass player_3P_AnimBP.player_3P_AnimBP_C
	 * Size -> 0xC8DC (FullSize[0xD8AC] - InheritedSize[0x0FD0])
	 */
	class Uplayer_3P_AnimBP_C : public URBAnimInstancePlayer3P
	{
	public:
		struct FPointerToUberGraphFrame                            UberGraphFrame;                                          // 0x0FD0(0x0008) ZeroConstructor, Transient, DuplicateTransient
		struct FAnimNode_Slot                                      AnimGraphNode_Slot_6;                                    // 0x0FD8(0x0048)
		struct FAnimNode_Slot                                      AnimGraphNode_Slot_5;                                    // 0x1020(0x0048)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_8;                        // 0x1068(0x00C0)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_9;                          // 0x1128(0x0158)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_7;                        // 0x1280(0x00C0)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_8;                          // 0x1340(0x0158)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_19;                          // 0x1498(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_100;                        // 0x14C0(0x0080)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_7;                          // 0x1540(0x0158)
		struct FAnimNode_LegIK                                     AnimGraphNode_LegIK_4;                                   // 0x1698(0x00F8)
		struct FAnimNode_LegIK                                     AnimGraphNode_LegIK_3;                                   // 0x1790(0x00F8)
		struct FAnimNode_ModifyBone                                AnimGraphNode_ModifyBone_5;                              // 0x1888(0x0108)
		struct FAnimNode_ConvertLocalToComponentSpace              AnimGraphNode_LocalToComponentSpace_6;                   // 0x1990(0x0020)
		struct FAnimNode_ConvertComponentToLocalSpace              AnimGraphNode_ComponentToLocalSpace_6;                   // 0x19B0(0x0020)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_6;                          // 0x19D0(0x0158)
		struct FAnimNode_ConvertLocalToComponentSpace              AnimGraphNode_LocalToComponentSpace_5;                   // 0x1B28(0x0020)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_6;                        // 0x1B48(0x00C0)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_18;                          // 0x1C08(0x0028)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_5;                          // 0x1C30(0x0158)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_5;                        // 0x1D88(0x00C0)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_17;                          // 0x1E48(0x0028)
		struct FAnimNode_Slot                                      AnimGraphNode_Slot_4;                                    // 0x1E70(0x0048)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_4;                        // 0x1EB8(0x00C0)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_99;                         // 0x1F78(0x0080)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_27;                        // 0x1FF8(0x00A8)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_26;                        // 0x20A0(0x00A8)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_142;                      // 0x2148(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_141;                      // 0x2170(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_98;                         // 0x2198(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_97;                         // 0x2218(0x0080)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_25;                        // 0x2298(0x00A8)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_3;                        // 0x2340(0x00C0)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_16;                          // 0x2400(0x0028)
		struct FAnimNode_ApplyAdditive                             AnimGraphNode_ApplyAdditive_4;                           // 0x2428(0x00C8)
		struct FAnimNode_BlendSpaceEvaluator                       AnimGraphNode_BlendSpaceEvaluator_3;                     // 0x24F0(0x00F0)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_24;                        // 0x25E0(0x00A8)
		struct FAnimNode_ApplyAdditive                             AnimGraphNode_ApplyAdditive_3;                           // 0x2688(0x00C8)
		struct FAnimNode_BlendSpaceEvaluator                       AnimGraphNode_BlendSpaceEvaluator_2;                     // 0x2750(0x00F0)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_15;                          // 0x2840(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_83;                            // 0x2868(0x0030)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_14;                          // 0x2898(0x0028)
		struct FAnimNode_RotationOffsetBlendSpace                  AnimGraphNode_RotationOffsetBlendSpace;                  // 0x28C0(0x0190)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_82;                            // 0x2A50(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_16;                           // 0x2A80(0x00B0)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_13;                          // 0x2B30(0x0028)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_4;                          // 0x2B58(0x0158)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_12;                          // 0x2CB0(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_11;                          // 0x2CD8(0x0028)
		struct FAnimNode_Slot                                      AnimGraphNode_Slot_3;                                    // 0x2D00(0x0048)
		struct FAnimNode_Slot                                      AnimGraphNode_Slot_2;                                    // 0x2D48(0x0048)
		struct FAnimNode_CopyPoseFromMesh                          AnimGraphNode_CopyPoseFromMesh_3;                        // 0x2D90(0x01D8) ContainsInstancedReference
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_3;                          // 0x2F68(0x0158)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_140;                      // 0x30C0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_139;                      // 0x30E8(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_96;                         // 0x3110(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_81;                            // 0x3190(0x0030)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_10;                          // 0x31C0(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_80;                            // 0x31E8(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_15;                           // 0x3218(0x00B0)
		struct FAnimNode_LinkedAnimGraph                           AnimGraphNode_LinkedAnimGraph;                           // 0x32C8(0x00A0)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_138;                      // 0x3368(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_137;                      // 0x3390(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_136;                      // 0x33B8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_135;                      // 0x33E0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_134;                      // 0x3408(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_133;                      // 0x3430(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_132;                      // 0x3458(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_131;                      // 0x3480(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_130;                      // 0x34A8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_129;                      // 0x34D0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_128;                      // 0x34F8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_127;                      // 0x3520(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_126;                      // 0x3548(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_125;                      // 0x3570(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_124;                      // 0x3598(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_123;                      // 0x35C0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_122;                      // 0x35E8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_121;                      // 0x3610(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_120;                      // 0x3638(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_119;                      // 0x3660(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_118;                      // 0x3688(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_117;                      // 0x36B0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_116;                      // 0x36D8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_115;                      // 0x3700(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_114;                      // 0x3728(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_113;                      // 0x3750(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_112;                      // 0x3778(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_111;                      // 0x37A0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_110;                      // 0x37C8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_109;                      // 0x37F0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_108;                      // 0x3818(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_107;                      // 0x3840(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_106;                      // 0x3868(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_105;                      // 0x3890(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_104;                      // 0x38B8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_103;                      // 0x38E0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_102;                      // 0x3908(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_101;                      // 0x3930(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_100;                      // 0x3958(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_99;                       // 0x3980(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_98;                       // 0x39A8(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_95;                         // 0x39D0(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_79;                            // 0x3A50(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_94;                         // 0x3A80(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_78;                            // 0x3B00(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_93;                         // 0x3B30(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_77;                            // 0x3BB0(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_92;                         // 0x3BE0(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_76;                            // 0x3C60(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_91;                         // 0x3C90(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_75;                            // 0x3D10(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_90;                         // 0x3D40(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_74;                            // 0x3DC0(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_89;                         // 0x3DF0(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_73;                            // 0x3E70(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_88;                         // 0x3EA0(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_72;                            // 0x3F20(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_87;                         // 0x3F50(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_71;                            // 0x3FD0(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_86;                         // 0x4000(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_85;                         // 0x4080(0x0080)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_23;                        // 0x4100(0x00A8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_70;                            // 0x41A8(0x0030)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_24;                       // 0x41D8(0x00E8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_69;                            // 0x42C0(0x0030)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_9;                           // 0x42F0(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_68;                            // 0x4318(0x0030)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_23;                       // 0x4348(0x00E8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_67;                            // 0x4430(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_14;                           // 0x4460(0x00B0)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_66;                            // 0x4510(0x0030)
		struct FAnimNode_ConvertComponentToLocalSpace              AnimGraphNode_ComponentToLocalSpace_5;                   // 0x4540(0x0020)
		struct FAnimNode_ConvertLocalToComponentSpace              AnimGraphNode_LocalToComponentSpace_4;                   // 0x4560(0x0020)
		struct FAnimNode_ModifyBone                                AnimGraphNode_ModifyBone_4;                              // 0x4580(0x0108)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_84;                         // 0x4688(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_65;                            // 0x4708(0x0030)
		struct FAnimNode_ConvertComponentToLocalSpace              AnimGraphNode_ComponentToLocalSpace_4;                   // 0x4738(0x0020)
		struct FAnimNode_ConvertLocalToComponentSpace              AnimGraphNode_LocalToComponentSpace_3;                   // 0x4758(0x0020)
		struct FAnimNode_ModifyBone                                AnimGraphNode_ModifyBone_3;                              // 0x4778(0x0108)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_22;                        // 0x4880(0x00A8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_22;                       // 0x4928(0x00E8)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_83;                         // 0x4A10(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_64;                            // 0x4A90(0x0030)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_21;                        // 0x4AC0(0x00A8)
		struct FAnimNode_BlendSpaceEvaluator                       AnimGraphNode_BlendSpaceEvaluator;                       // 0x4B68(0x00F0)
		struct FAnimNode_SequenceEvaluator                         AnimGraphNode_SequenceEvaluator_8;                       // 0x4C58(0x0050)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_63;                            // 0x4CA8(0x0030)
		struct FAnimNode_SequenceEvaluator                         AnimGraphNode_SequenceEvaluator_7;                       // 0x4CD8(0x0050)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_62;                            // 0x4D28(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_82;                         // 0x4D58(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_61;                            // 0x4DD8(0x0030)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_21;                       // 0x4E08(0x00E8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_60;                            // 0x4EF0(0x0030)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_97;                       // 0x4F20(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_96;                       // 0x4F48(0x0028)
		struct FAnimNode_SequenceEvaluator                         AnimGraphNode_SequenceEvaluator_6;                       // 0x4F70(0x0050)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_59;                            // 0x4FC0(0x0030)
		struct FAnimNode_SequenceEvaluator                         AnimGraphNode_SequenceEvaluator_5;                       // 0x4FF0(0x0050)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_58;                            // 0x5040(0x0030)
		struct FAnimNode_RefPose                                   AnimGraphNode_LocalRefPose_2;                            // 0x5070(0x0018)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_57;                            // 0x5088(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_13;                           // 0x50B8(0x00B0)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_56;                            // 0x5168(0x0030)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_8;                           // 0x5198(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_55;                            // 0x51C0(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_12;                           // 0x51F0(0x00B0)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_2;                          // 0x52A0(0x0158)
		struct FAnimNode_Slot                                      AnimGraphNode_Slot;                                      // 0x53F8(0x0048)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_95;                       // 0x5440(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_94;                       // 0x5468(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_93;                       // 0x5490(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_92;                       // 0x54B8(0x0028)
		struct FAnimNode_ConvertComponentToLocalSpace              AnimGraphNode_ComponentToLocalSpace_3;                   // 0x54E0(0x0020)
		struct FAnimNode_ConvertLocalToComponentSpace              AnimGraphNode_LocalToComponentSpace_2;                   // 0x5500(0x0020)
		struct FAnimNode_TwoBoneIK                                 AnimGraphNode_TwoBoneIK_2;                               // 0x5520(0x01E0)
		struct FAnimNode_TwoBoneIK                                 AnimGraphNode_TwoBoneIK;                                 // 0x5700(0x01E0)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_81;                         // 0x58E0(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_54;                            // 0x5960(0x0030)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_91;                       // 0x5990(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_90;                       // 0x59B8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_89;                       // 0x59E0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_88;                       // 0x5A08(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_87;                       // 0x5A30(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_86;                       // 0x5A58(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_85;                       // 0x5A80(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_84;                       // 0x5AA8(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_80;                         // 0x5AD0(0x0080)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_20;                        // 0x5B50(0x00A8)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_79;                         // 0x5BF8(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_53;                            // 0x5C78(0x0030)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_7;                           // 0x5CA8(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_52;                            // 0x5CD0(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_78;                         // 0x5D00(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_51;                            // 0x5D80(0x0030)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_83;                       // 0x5DB0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_82;                       // 0x5DD8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_81;                       // 0x5E00(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_80;                       // 0x5E28(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_79;                       // 0x5E50(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_78;                       // 0x5E78(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_77;                       // 0x5EA0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_76;                       // 0x5EC8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_75;                       // 0x5EF0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_74;                       // 0x5F18(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_73;                       // 0x5F40(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_72;                       // 0x5F68(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_71;                       // 0x5F90(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_70;                       // 0x5FB8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_69;                       // 0x5FE0(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_77;                         // 0x6008(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_76;                         // 0x6088(0x0080)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_19;                        // 0x6108(0x00A8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_50;                            // 0x61B0(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_75;                         // 0x61E0(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_49;                            // 0x6260(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_74;                         // 0x6290(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_48;                            // 0x6310(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_73;                         // 0x6340(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_47;                            // 0x63C0(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_72;                         // 0x63F0(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_46;                            // 0x6470(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_71;                         // 0x64A0(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_45;                            // 0x6520(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_70;                         // 0x6550(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_44;                            // 0x65D0(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_69;                         // 0x6600(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_43;                            // 0x6680(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_68;                         // 0x66B0(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_42;                            // 0x6730(0x0030)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_18;                        // 0x6760(0x00A8)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_2;                        // 0x6808(0x00C0)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_67;                         // 0x68C8(0x0080)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_6;                           // 0x6948(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_66;                         // 0x6970(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_41;                            // 0x69F0(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_65;                         // 0x6A20(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_40;                            // 0x6AA0(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_11;                           // 0x6AD0(0x00B0)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_39;                            // 0x6B80(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_64;                         // 0x6BB0(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_38;                            // 0x6C30(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_10;                           // 0x6C60(0x00B0)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_37;                            // 0x6D10(0x0030)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_5;                           // 0x6D40(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_36;                            // 0x6D68(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_9;                            // 0x6D98(0x00B0)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_68;                       // 0x6E48(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_67;                       // 0x6E70(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_66;                       // 0x6E98(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_65;                       // 0x6EC0(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_63;                         // 0x6EE8(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_62;                         // 0x6F68(0x0080)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_17;                        // 0x6FE8(0x00A8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_35;                            // 0x7090(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_61;                         // 0x70C0(0x0080)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_16;                        // 0x7140(0x00A8)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_60;                         // 0x71E8(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_34;                            // 0x7268(0x0030)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_4;                           // 0x7298(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_33;                            // 0x72C0(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_8;                            // 0x72F0(0x00B0)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_3;                           // 0x73A0(0x0028)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose;                            // 0x73C8(0x0158)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_64;                       // 0x7520(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_63;                       // 0x7548(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_62;                       // 0x7570(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_61;                       // 0x7598(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_60;                       // 0x75C0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_59;                       // 0x75E8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_58;                       // 0x7610(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_57;                       // 0x7638(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_56;                       // 0x7660(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_55;                       // 0x7688(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_54;                       // 0x76B0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_53;                       // 0x76D8(0x0028)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_20;                       // 0x7700(0x00E8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_19;                       // 0x77E8(0x00E8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_18;                       // 0x78D0(0x00E8)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_59;                         // 0x79B8(0x0080)
		struct FAnimNode_BlendListByEnum                           AnimGraphNode_BlendListByEnum_5;                         // 0x7A38(0x00B8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_32;                            // 0x7AF0(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_58;                         // 0x7B20(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_57;                         // 0x7BA0(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_56;                         // 0x7C20(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_55;                         // 0x7CA0(0x0080)
		struct FAnimNode_BlendListByEnum                           AnimGraphNode_BlendListByEnum_4;                         // 0x7D20(0x00B8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_17;                       // 0x7DD8(0x00E8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_16;                       // 0x7EC0(0x00E8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_15;                       // 0x7FA8(0x00E8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_14;                       // 0x8090(0x00E8)
		struct FAnimNode_BlendListByEnum                           AnimGraphNode_BlendListByEnum_3;                         // 0x8178(0x00B8)
		struct FAnimNode_BlendListByEnum                           AnimGraphNode_BlendListByEnum_2;                         // 0x8230(0x00B8)
		struct FAnimNode_BlendListByEnum                           AnimGraphNode_BlendListByEnum;                           // 0x82E8(0x00B8)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_54;                         // 0x83A0(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_31;                            // 0x8420(0x0030)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_15;                        // 0x8450(0x00A8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_13;                       // 0x84F8(0x00E8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_12;                       // 0x85E0(0x00E8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_30;                            // 0x86C8(0x0030)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_52;                       // 0x86F8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_51;                       // 0x8720(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_50;                       // 0x8748(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_49;                       // 0x8770(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_48;                       // 0x8798(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_47;                       // 0x87C0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_46;                       // 0x87E8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_45;                       // 0x8810(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_44;                       // 0x8838(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_43;                       // 0x8860(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_42;                       // 0x8888(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_41;                       // 0x88B0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_40;                       // 0x88D8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_39;                       // 0x8900(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_38;                       // 0x8928(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_37;                       // 0x8950(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_36;                       // 0x8978(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_35;                       // 0x89A0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_34;                       // 0x89C8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_33;                       // 0x89F0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_32;                       // 0x8A18(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_31;                       // 0x8A40(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_30;                       // 0x8A68(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_29;                       // 0x8A90(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_28;                       // 0x8AB8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_27;                       // 0x8AE0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_26;                       // 0x8B08(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_25;                       // 0x8B30(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_24;                       // 0x8B58(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_23;                       // 0x8B80(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_22;                       // 0x8BA8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_21;                       // 0x8BD0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_20;                       // 0x8BF8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_19;                       // 0x8C20(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_18;                       // 0x8C48(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_17;                       // 0x8C70(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_16;                       // 0x8C98(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_15;                       // 0x8CC0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_14;                       // 0x8CE8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_13;                       // 0x8D10(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_12;                       // 0x8D38(0x0028)
		struct FAnimNode_RefPose                                   AnimGraphNode_LocalRefPose;                              // 0x8D60(0x0018)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_29;                            // 0x8D78(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_53;                         // 0x8DA8(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_28;                            // 0x8E28(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_52;                         // 0x8E58(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_27;                            // 0x8ED8(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_51;                         // 0x8F08(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_50;                         // 0x8F88(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_49;                         // 0x9008(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_48;                         // 0x9088(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_47;                         // 0x9108(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_46;                         // 0x9188(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_45;                         // 0x9208(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_44;                         // 0x9288(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_43;                         // 0x9308(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_42;                         // 0x9388(0x0080)
		struct FAnimNode_BlendListByInt                            AnimGraphNode_BlendListByInt_3;                          // 0x9408(0x00A8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_26;                            // 0x94B0(0x0030)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_11;                       // 0x94E0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_10;                       // 0x9508(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_41;                         // 0x9530(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_40;                         // 0x95B0(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_39;                         // 0x9630(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_38;                         // 0x96B0(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_37;                         // 0x9730(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_36;                         // 0x97B0(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_35;                         // 0x9830(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_34;                         // 0x98B0(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_33;                         // 0x9930(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_32;                         // 0x99B0(0x0080)
		struct FAnimNode_BlendListByInt                            AnimGraphNode_BlendListByInt_2;                          // 0x9A30(0x00A8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_25;                            // 0x9AD8(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_31;                         // 0x9B08(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_30;                         // 0x9B88(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_29;                         // 0x9C08(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_28;                         // 0x9C88(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_27;                         // 0x9D08(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_26;                         // 0x9D88(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_25;                         // 0x9E08(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_24;                         // 0x9E88(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_23;                         // 0x9F08(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_22;                         // 0x9F88(0x0080)
		struct FAnimNode_BlendListByInt                            AnimGraphNode_BlendListByInt;                            // 0xA008(0x00A8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_24;                            // 0xA0B0(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_7;                            // 0xA0E0(0x00B0)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_23;                            // 0xA190(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_21;                         // 0xA1C0(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_22;                            // 0xA240(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_20;                         // 0xA270(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_21;                            // 0xA2F0(0x0030)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_9;                        // 0xA320(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_19;                         // 0xA348(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_20;                            // 0xA3C8(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_18;                         // 0xA3F8(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_19;                            // 0xA478(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_17;                         // 0xA4A8(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_18;                            // 0xA528(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_16;                         // 0xA558(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_17;                            // 0xA5D8(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_15;                         // 0xA608(0x0080)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_14;                        // 0xA688(0x00A8)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_14;                         // 0xA730(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_16;                            // 0xA7B0(0x0030)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_8;                        // 0xA7E0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_7;                        // 0xA808(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_13;                         // 0xA830(0x0080)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_13;                        // 0xA8B0(0x00A8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_11;                       // 0xA958(0x00E8)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_12;                        // 0xAA40(0x00A8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_10;                       // 0xAAE8(0x00E8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_15;                            // 0xABD0(0x0030)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_11;                        // 0xAC00(0x00A8)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_12;                         // 0xACA8(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_11;                         // 0xAD28(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_14;                            // 0xADA8(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_6;                            // 0xADD8(0x00B0)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_13;                            // 0xAE88(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_10;                         // 0xAEB8(0x0080)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_10;                        // 0xAF38(0x00A8)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_9;                          // 0xAFE0(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_12;                            // 0xB060(0x0030)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_9;                         // 0xB090(0x00A8)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_8;                          // 0xB138(0x0080)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_7;                          // 0xB1B8(0x0080)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_8;                         // 0xB238(0x00A8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_9;                        // 0xB2E0(0x00E8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_11;                            // 0xB3C8(0x0030)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_6;                        // 0xB3F8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_5;                        // 0xB420(0x0028)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_8;                        // 0xB448(0x00E8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_7;                        // 0xB530(0x00E8)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_7;                         // 0xB618(0x00A8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_10;                            // 0xB6C0(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_6;                          // 0xB6F0(0x0080)
		struct FAnimNode_SequenceEvaluator                         AnimGraphNode_SequenceEvaluator_4;                       // 0xB770(0x0050)
		struct FAnimNode_SequenceEvaluator                         AnimGraphNode_SequenceEvaluator_3;                       // 0xB7C0(0x0050)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_6;                         // 0xB810(0x00A8)
		struct FAnimNode_ApplyAdditive                             AnimGraphNode_ApplyAdditive_2;                           // 0xB8B8(0x00C8)
		struct FAnimNode_MakeDynamicAdditive                       AnimGraphNode_MakeDynamicAdditive_2;                     // 0xB980(0x0038)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_5;                          // 0xB9B8(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_9;                             // 0xBA38(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_5;                            // 0xBA68(0x00B0)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_8;                             // 0xBB18(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_4;                            // 0xBB48(0x00B0)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_7;                             // 0xBBF8(0x0030)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_4;                        // 0xBC28(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_3;                        // 0xBC50(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_2;                        // 0xBC78(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult;                          // 0xBCA0(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_4;                          // 0xBCC8(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_6;                             // 0xBD48(0x0030)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_6;                        // 0xBD78(0x00E8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_5;                        // 0xBE60(0x00E8)
		struct FAnimNode_TwoWayBlend                               AnimGraphNode_TwoWayBlend_2;                             // 0xBF48(0x00C8)
		struct FAnimNode_TwoWayBlend                               AnimGraphNode_TwoWayBlend;                               // 0xC010(0x00C8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_4;                        // 0xC0D8(0x00E8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_3;                        // 0xC1C0(0x00E8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_2;                        // 0xC2A8(0x00E8)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_5;                         // 0xC390(0x00A8)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_4;                         // 0xC438(0x00A8)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_3;                         // 0xC4E0(0x00A8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer;                          // 0xC588(0x00E8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_5;                             // 0xC670(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_3;                          // 0xC6A0(0x0080)
		struct FAnimNode_SequenceEvaluator                         AnimGraphNode_SequenceEvaluator_2;                       // 0xC720(0x0050)
		struct FAnimNode_SequenceEvaluator                         AnimGraphNode_SequenceEvaluator;                         // 0xC770(0x0050)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_2;                         // 0xC7C0(0x00A8)
		struct FAnimNode_ApplyAdditive                             AnimGraphNode_ApplyAdditive;                             // 0xC868(0x00C8)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_2;                          // 0xC930(0x0080)
		struct FAnimNode_MakeDynamicAdditive                       AnimGraphNode_MakeDynamicAdditive;                       // 0xC9B0(0x0038)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_4;                             // 0xC9E8(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_3;                            // 0xCA18(0x00B0)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_3;                             // 0xCAC8(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_2;                            // 0xCAF8(0x00B0)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_2;                             // 0xCBA8(0x0030)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer;                            // 0xCBD8(0x0080)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult;                               // 0xCC58(0x0030)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine;                              // 0xCC88(0x00B0)
		struct FAnimNode_Root                                      AnimGraphNode_Root;                                      // 0xCD38(0x0030)
		struct FAnimNode_ConvertComponentToLocalSpace              AnimGraphNode_ComponentToLocalSpace_2;                   // 0xCD68(0x0020)
		struct FAnimNode_RBRotateRelative                          AnimGraphNode_RBRotateRelative;                          // 0xCD88(0x00F8)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_2;                           // 0xCE80(0x0028)
		struct FAnimNode_CopyPoseFromMesh                          AnimGraphNode_CopyPoseFromMesh_2;                        // 0xCEA8(0x01D8) ContainsInstancedReference
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend;                          // 0xD080(0x00C0)
		struct FAnimNode_LegIK                                     AnimGraphNode_LegIK_2;                                   // 0xD140(0x00F8)
		struct FAnimNode_ConvertLocalToComponentSpace              AnimGraphNode_LocalToComponentSpace;                     // 0xD238(0x0020)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool;                           // 0xD258(0x00A8)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose;                             // 0xD300(0x0028)
		struct FAnimNode_ConvertComponentToLocalSpace              AnimGraphNode_ComponentToLocalSpace;                     // 0xD328(0x0020)
		struct FAnimNode_LegIK                                     AnimGraphNode_LegIK;                                     // 0xD348(0x00F8)
		struct FAnimNode_CopyPoseFromMesh                          AnimGraphNode_CopyPoseFromMesh;                          // 0xD440(0x01D8) ContainsInstancedReference
		struct FAnimNode_ModifyBone                                AnimGraphNode_ModifyBone_2;                              // 0xD618(0x0108)
		struct FAnimNode_ModifyBone                                AnimGraphNode_ModifyBone;                                // 0xD720(0x0108)
		bool                                                       IsAFK;                                                   // 0xD828(0x0001) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor
		unsigned char                                              UnknownData_DYU6[0x7];                                   // 0xD829(0x0007) MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
		struct FTimerHandle                                        IdleTimer;                                               // 0xD830(0x0008) Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash
		bool                                                       IsShopping;                                              // 0xD838(0x0001) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor
		unsigned char                                              UnknownData_64IC[0x3];                                   // 0xD839(0x0003) MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
		int32_t                                                    AFKStyle;                                                // 0xD83C(0x0004) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash
		float                                                      DelayedPeek;                                             // 0xD840(0x0004) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash
		float                                                      LookBlend;                                               // 0xD844(0x0004) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash
		TMap<EItemType, class UAnimSequenceBase*>                  ItemTypeStyle;                                           // 0xD848(0x0050) Edit, BlueprintVisible, DisableEditOnInstance
		float                                                      PickUpBlend;                                             // 0xD898(0x0004) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash
		unsigned char                                              UnknownData_DIFQ[0x4];                                   // 0xD89C(0x0004) MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
		class UAnimSequenceBase*                                   PickUpHand;                                              // 0xD8A0(0x0008) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash
		int32_t                                                    IdleStyle;                                               // 0xD8A8(0x0004) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash

	public:
		void AnimGraph(struct FPoseLink* AnimGraph);
		void ToggleAFK();
		bool ShouldIgnoreLookAround();
		void AnimNotify_IsGone();
		void AnimNotify_IsIdle();
		void AnimNotify_IsBack();
		void BlueprintUpdateAnimation(float DeltaTimeX);
		void AnimNotify_Dead();
		void AnimNotify_Alive();
		void AnimNotify_IdleBreaker();
		void ExecuteUbergraph_player_3P_AnimBP(int32_t EntryPoint);
		static UClass* StaticClass();
	};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
